name: remedi_vimeo_player
description: Vimeo player without iframe
version: 0.0.4+1
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_plugins'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_plugins'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # video player
  better_player: ^0.0.72
  # http
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.remedi.vimeo_player
        pluginClass: RemediVimeoPlayerPlugin
      ios:
        pluginClass: RemediVimeoPlayerPlugin
      web:
        pluginClass: RemediVimeoPlayerWeb
        fileName: remedi_vimeo_player_web.dart