name: remedi_localization
version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - flags/
  plugin:
    platforms:
      android:
        package: com.remedi.localization
        pluginClass: RemediLocalizationPlugin
      ios:
        pluginClass: RemediLocalizationPlugin
