name: multiscreen
description: Support multiscreen(different resolution and size of display) for mobile application.
version: 2.0.0
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_plugins'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_plugins'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.tossy.flutter.multiscreen
        pluginClass: MultiscreenPlugin
      ios:
        pluginClass: MultiscreenPlugin

